### ISSUE TITLE
Hash doesn't seem to recalculate

### ISSUE THREAD

**Issue by KallDrexx** [janjongboom/Moth#2]
Moth seems to be a bit hard to use in a development environment.  It doesn't seem to detect when a javascript file has changed.   So minor changes to a javascript file will not be seen unless you do a complete rebuild, making iterative development hard.  Refreshing the page (and the cshtml) still links to the pre-modified script.  Taking the hash out of the href correctly gets the updated script, but even after that refreshing the page still link to the pre-modified script.

I have PageOutput = false set in my custom AspNetCacheProvider class.

**Comment by janjongboom** [comment]
Hi Matthew,

The javascript files are cached for 10 minutes, because the minification can
be quite heavy (this is regulated in 'CacheDurations.ExternalScript'
https://github.com/janjongboom/Moth/wiki/Options. The reason they
are immediately refreshed on rebuild is because ASPNET cache is refreshed at
that point.

Would you let me know whether the files were changed automatically after 10
minutes? For faster expiration of the cache I might be able to work
something out with FileSystemWatchers, but I'm not at my workstation right
now.

Kind regards,

2011/9/14 Matthew Shapiro <
reply@reply.github.com>

**Comment by KallDrexx** [comment]
I didn't wait around to see if the 10 minute limit would refresh it (I didn't know how long the cache time was) so I can't answer that.  

However, I did seem to miss the option for modifying the cache duration, so when I get home I'll play with that.  Right now I have a provider setup so that if I am running in Debug mode no minification occurs, so I will probably do the same thing for cache duration (no cache duration in debug mode) and that would probably do just fine for my development purposes.  I'll close this if that works fine, as I do wonder what the overhead of the FileSystemWatchers would be.

**Comment by KallDrexx** [comment]
Setting the cache duration to zero for debug builds successfully makes development scripts update immediately.  So I'm good :)
