### ISSUE TITLE
Javascript files are not refreshed

### ISSUE THREAD

**Issue by moshatwork** [janjongboom/Moth#3]
Hello, 

When I update one of my Javascript files (ie. change **alert("Hello World")** to **alert("Hello World UPDATED")**, I still get the old version in the combined script. 

I noticed the hash appended to the URL is not changed. In fact, hash is calculated based on the **KEYS** passed in, not the actual content of the files. I believe this is not the right approach. 

Is there anything I'm missing here?

Cheers,
Mosh

**Comment by janjongboom** [comment]
This issue is a clone of https://github.com/janjongboom/Moth/issues/2#issuecomment-2100232

Hi Mosh,

Thanks for using Moth :-). The javascript files are cached for around 10 minutes, because it takes some time to minify them. After this period the files and the hash are updated. The reason that you see the changes immediately when you change the keys, is that the cache-key is calculated out of the keys, the hashing is done on the raw content of your js files.

You can do an immediate refresh by recycling your web app (change web.config so the process restarts), or when in debug, use the debug flags (https://github.com/janjongboom/Moth/wiki/Debug-flags).

Please let me know whether this resolves your problems.

Regards,
